### ISSUE TITLE
IO9 not working

### ISSUE THREAD

**Issue by lemanhtien** [frenetisch-applaudierend/ios-drag-and-drop#7] opened 2016-04-08 04:14 UTC
Please check your Lib in IOs 9.  I tested in IP 6s 9.2.1 , the library is not working if my drag source is tableview or collection view. You sample example is not working in IOs 9 too (DNDTableViewController). 
Please check it. 
Hope to see your reply soon.
Thank you.

**Comment by frenetisch-applaudierend** [comment] 2016-04-08 07:37
Hey lemanhtien, thanks for your feedback.

I just checked it, and I can't find anything wrong, apart from that the sample app is not really phone friendly. The drag & drop works fine for me though, at least in landscape.

Do you have some more information what you're experiencing vs what you expected?

**Comment by lemanhtien** [comment] 2016-04-08 07:45
In IOs 9.2.1, if you change `[self.dragAndDropController registerDragSource:tableView withDelegate:self dragRecognizer:dragRecognizer];` to `    [self.dragAndDropController registerDragSource:tableView withDelegate:self]` , it will work. I don't have so much experience with UIGestureRecognizer but i think the problem is caused by DNDLongPressDragRecognizer. 
When i detect , the `state` in DNDLongPressDragRecognizer always is UIGestureRecognizerStatePossible ( It only appears in IOs 9.2.1,in IOs 8.4 , i works normally ).

**Comment by frenetisch-applaudierend** [comment] 2016-04-08 08:01
I don't have a device running iOS 9.2.1, but I tried to reproduce it on the 9.2 simulator and on a device with iOS 9.3.1 installed, but no luck.

The long press recognizer requires you to touch and hold the item for a short while before you can start dragging. If you start dragging directly it won't register. This is so the gesture recognizer does not compete for touches with the scrolling of the table view. Maybe that is the issue? (the default time of the recognizer is very long)

**Comment by deeje** [comment] 2016-07-13 17:21
I'm seeing the same thing.  DNDLongPressDragRecognizer works on an iPhone 6, but not on a 6s

**Comment by deeje** [comment] 2016-07-13 17:22
fwiw, on 3D touch devices, touchesMoved gets called even when the touch hasn't moved, per se, but still delivers force data

**Comment by frenetisch-applaudierend** [comment] 2016-07-21 11:11
@lemanhtien I just pushed version 1.2.2 which includes the touchesMoved fix, it may solve your problem. If you get around to trying it, I'm curious wether it worked.

Thank you @deeje for the contribution of the fix.

**Comment by frenetisch-applaudierend** [comment] 2016-10-24 17:28
I just checked it with a force touch enabled device and cannot reproduce issue anymore, so I'm closing this issue. If the issue pops up again feel free to reopen it.

**Closed by frenetisch-applaudierend** 2016-10-24 17:28 UTC
